# Streamlit configuration for Quran Tafsir Search
[theme]
base = "dark"
primaryColor = "#0A84FF"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#F2F2F7"
font = "sans serif"

# Enhanced font configuration for better Arabic text display
baseFontSize = 20  # Increased from default 16px for better Arabic readability

[server]
headless = true
port = 8501
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
